### ISSUE TITLE
Add optional dependencies to pyproject.toml

### ISSUE THREAD

**Issue by mattfalcone1997** [osandrei/python-intermediate-inflammation#10]
We should also consider adding the optional dependencies to the `pyproject.toml`:

```toml
[project.optional-dependencies]
# development dependency groups
test = [
    'pytest',
    'pytest-cov'
]
```
