### ISSUE TITLE
Add package dependencies to pyproject.toml

### ISSUE THREAD

**Issue by mattfalcone1997** [osandrei/python-intermediate-inflammation#9]
Dependencies are not listed in the `pyproject.toml` file. The dependencies are currently installed separately through a `requirements.txt` file. We should either be replace the file or the following should be added to the `pyproject.toml`:
```toml
[project]
dynamic = ["dependencies"]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
```
